### ISSUE TITLE
Feature Request - Setting to Change Emoji 

### ISSUE THREAD

**Issue by trudeaua21** [alDuncanson/cuppa#5]
![Screen Shot 2022-02-02 at 4 48 56 PM](https://user-images.githubusercontent.com/36064197/152243027-783543a0-9e19-49df-ae69-7ecdeb843d18.png)

It would be cool if I could put whatever emoji I want here :)

**Comment by alDuncanson** [comment]
Oooo love that idea! I'll start work on that this week 🙂

**Comment by alDuncanson** [comment]
@trudeaua21 so time has gotten away from me a bit 😅 

If I find some time to dedicate to this project again I will definitely implement this!

**Comment by alDuncanson** [comment]
I've added custom emoji support: c8d83ad

This will be available in the next release :)
